### ISSUE TITLE
[docs] Contents navigation hidden on mobile

### ISSUE THREAD

**Issue by palimondo** [scala/docs.scala-lang#1054]
When reading the [Scala collections documentation](https://docs.scala-lang.org/overviews/collections/introduction.html) on mobile, I can not navigate between chapters. It appears that when the display is narrower than 768px, the table of contents disappears completely. From style.css:
```` css
@media (max-width: 768px) {
  .sidebar-toc-wrapper {
    display: none; } }
````
